# Generated by Django 2.2.11 on 2020-03-17 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200316_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='day_working_hours',
        ),
        migrations.RemoveField(
            model_name='user',
            name='day_working_minutes',
        ),
        migrations.AddField(
            model_name='user',
            name='day_working_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
