# Generated by Django 2.2.11 on 2020-03-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200317_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_flexibility',
            field=models.BooleanField(default=False),
        ),
    ]
