# Generated by Django 2.2.11 on 2020-03-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_time_flexibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_tasks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
