# Generated by Django 2.2.11 on 2020-03-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='digest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
